package org.edu.ncu.part1

import java.io.Serializable


data class RPlayList(var playlists: List<PlayLists>,
                    var total: Int,
                    var code: Int
                    ,var more: Boolean
                    ,var cat: String): Serializable {
    data class PlayLists(var name: String,
                         var id: Long,
                         var trackNumberUpdateTime: Long,
                         var status: Int,
                         var userId: Int,
                         var createTime: Long,
                         var updateTime: Long,
                         var subscribedCount: Int,
                         var trackCount: Int,
                         var cloudTrackCount: Int,
                         var coverImgUrl: String,
                         var coverImgId: Long,
                         var description: String,
                         var tag: List<String>,
                         var playCount: Int,
                         var trackUpdateTime: Long,
                         var specialType: Int,
                         var totalDuration: Int,
                         var creator: Creator,
                         var tracks: String,
                         var subscribers: List<String>,
                         var subscribed: String,
                         var commentThreadId: String,
                         var newImported: Boolean,
                         var adType: Int,
                         var highQuality: Boolean,
                         var privacy: Int,
                         var ordered: Boolean,
                         var anonimous: Boolean,
                         var coverStatus: Int,
                         var recommendInfo: String,
                         var shareCount: Int,
                         var commentCount: Int): Serializable{
        data class Creator(var defaultAvatar: Boolean,
                           var province: Int,
                           var authStatus: Int,
                           var followed: Boolean,
                           var avatarUrl: String,
                           var accountStatus: Int,
                           var gender: Int,
                           var city: Int,
                           var birthday: Long,
                           var userId: Int,
                           var userType: Int,
                           var nickname: String,
                           var signature: String,
                           var description: String,
                           var detailDescription: String,
                           var avatarImgId: Long,
                           var backgroundImgId: Long,
                           var backgroundUrl: String,
                           var authority: Int,
                           var mutual: Boolean,
                           var expertTags: String,
                           var experts: String,
                           var djStatus: Int,
                           var vipType: Int,
                           var remarkName: String,
                           var authenticationTypes: Int,
                           var avatarDetail: String,
                           var avatarImgIdStr: String,
                           var backgroundImgIdStr: String,
                           var anchor: Boolean,
                           var avatarImgId_str: String): Serializable
    }

}